from database import get_connection

def init_db():
    with get_connection() as connection:
        with connection.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS customers (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    phone TEXT,
                    smoking_preference TEXT,
                    notes TEXT
                )
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS stays (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id INTEGER NOT NULL,
                    stay_date DATE NOT NULL,
                    notes TEXT,
                    FOREIGN KEY (customer_id)
                        REFERENCES customers(id)
                )
            """)

    print("テーブル作成成功！")

if __name__ == "__main__":
    init_db()